# Generated by Django 6.0.2 on 2026-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_category_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
