# Generated by Django 6.0.2 on 2026-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
