# Generated by Django 6.0.2 on 2026-02-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_feature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
