# Generated by Django 6.0.2 on 2026-02-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
