# Generated by Django 6.0.2 on 2026-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventtag_event_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/extra-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='extraImages',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.eventimages'),
        ),
    ]
