# Generated by Django 6.0.2 on 2026-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventimages_event_extraimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventtag',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
