# Generated by Django 6.0.2 on 2026-02-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_eventimages_options_alter_eventtag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
