# Generated by Django 6.0.2 on 2026-02-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
