# Generated by Django 6.0.2 on 2026-02-16 08:58

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_eventtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
