# Generated by Django 6.0.1 on 2026-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
